version: '3'
services:

  # jenkins docker:dind
  jenkins-docker:
    container_name: jenkins-docker
    image: docker:dind
    privileged: true
    restart: always
    networks:
      jenkins:
        aliases:
           - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    ports:
      - "2376:2376"
    command: ["--storage-driver", "overlay2"]
  
  # Jenkins blueocean
  jenkins-blueocean:
    container_name: jenkins-blueocean
    image: jenkins/jenkins
    build: 
      context: .
      dockerfile: ./jenkins-image/Dockerfile
    restart: always
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376 # docker refer to jenkins-docker network aliases
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
    ports:
      - "9000:8080"
      - "49000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
      - "$HOME:/home"
    depends_on:
      - jenkins-docker

  # Prometheus for jenkins monitoring
  jenkins-prometheus:
    container_name: jenkins-prometheus
    image: prom/prometheus:latest
    restart: always
    ports:
      - "9091:9090"
    volumes:
      - ./jenkins-prometheus:/etc/prometheus
    networks:
      - jenkins

  # Grafana for jenkins monitoring
  jenkins-grafana:
    container_name: jenkins-grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3031:3030"
    environment:
      - GF_SERVER_HTTP_PORT=3031
    networks:
      - jenkins

networks:
  jenkins:

volumes:
  jenkins-docker-certs:
  jenkins-data:
